Movie-Recommendation/Movie-Recommendation/MRS/urls.py
from django.contrib import admin
from django.urls import path
from MovieRecommender import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('',views.user_login, name='login' ),
    path('admin/', admin.site.urls),
    path('signup/',views.signup,name="signup"),
    path('login/',views.user_login,name="login"),
    path('home/',views.home,name="home"),
    path('dashboard/',views.dashboard,name="dashboard"),
    path("addmovie/",views.addmovie,name="addmovie"),
    path("logout/",views.user_logout,name="logout"),
    path("profile/",views.profile,name="profile")
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Movie-Recommendation/Movie-Recommendation/MovieRecommender/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Movie(models.Model):
    title=models.CharField(max_length=70)
    genres=models.CharField(max_length=70)
    year=models.CharField(max_length=70)
    image=models.ImageField(upload_to="movie_image")
    movieduration=models.CharField(max_length=70)
    def __str__(self):
        return str(self.pk)

class Rating(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,default=None)
    movie=models.ForeignKey(Movie,on_delete=models.CASCADE,default=None)
    rating=models.CharField(max_length=70)
    rated_date=models.DateTimeField(auto_now_add=True)

Movie-Recommendation/Movie-Recommendation/MovieRecommender/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Movie,Rating
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
class SignUpForm(UserCreationForm):
    password1=forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2=forms.CharField(label='Confirm Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model=User
        fields=['username','email']
        labels={'email':'Email Address'}
        widgets={
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
        }

class AddMovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields='__all__'
        labels={'title':'Movie Title','image':'Image','movieduration':'Duration'}
        widgets={
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'genres':forms.TextInput(attrs={'class':'form-control'}),
            'year':forms.TextInput(attrs={'class':'form-control'}),
            'image':forms.FileInput(attrs={'class':'form-control'}),
            'movieduration':forms.TextInput(attrs={'class':'form-control'})
        }

class LoginForm(AuthenticationForm):
    username=forms.CharField(label='Username',widget=forms.TextInput(attrs={'class':'form-control'}))
    password=forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        fields=['username','password']


class AddRatingForm(forms.ModelForm):
  
    class Meta:
        model=Rating
        fields=['rating']
        labels={'rating':'Rating'}
        widgets={
            'rating':forms.TextInput(attrs={'type':'range','step':'1','min':'0','max':'5','class':{'custom-range','border-0'}})
        }

Movie-Recommendation/Movie-Recommendation/MovieRecommender/views.py
from django.shortcuts import render,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout,update_session_auth_hash
from django.contrib.auth.models import User,Group
from .forms import SignUpForm,AddMovieForm,LoginForm,AddRatingForm
from .models import Movie,Rating
from django.contrib import messages
import pandas as pd
from math import sqrt
import numpy as np
import matplotlib.pyplot as plt
from math import ceil
# Create your views here.

def filterMovieByGenre():
     #filtering by genres
    allMovies=[]
    genresMovie= Movie.objects.values('genres', 'id')
    genres= {item["genres"] for item in genresMovie}
    for genre in genres:
        movie=Movie.objects.filter(genres=genre)
        print(movie)
        n = len(movie)
        nSlides = n // 4 + ceil((n / 4) - (n // 4))
        allMovies.append([movie, range(1, nSlides), nSlides])
    params={'allMovies':allMovies }
    return params


def generateRecommendation(request):
    movie=Movie.objects.all()
    rating=Rating.objects.all()
    x=[] 
    y=[]
    A=[]
    B=[]
    C=[]
    D=[]
    #Movie Data Frames
    for item in movie:
        x=[item.id,item.title,item.movieduration,item.image.url,item.genres] 
        y+=[x]
    movies_df = pd.DataFrame(y,columns=['movieId','title','movieduration','image','genres'])
    print("Movies DataFrame")
    print(movies_df)
    print(movies_df.dtypes)
    #Rating Data Frames
    print(rating)
    for item in rating:
        A=[item.user.id,item.movie,item.rating]
        B+=[A]
    rating_df=pd.DataFrame(B,columns=['userId','movieId','rating'])
    print("Rating data Frame")
    rating_df['userId']=rating_df['userId'].astype(str).astype(np.int64)
    rating_df['movieId']=rating_df['movieId'].astype(str).astype(np.int64)
    rating_df['rating']=rating_df['rating'].astype(str).astype(np.float)
    print(rating_df)
    print(rating_df.dtypes)
    if request.user.is_authenticated:
        userid=request.user.id
        #select related is join statement in django.It looks for foreign key and join the table
        userInput=Rating.objects.select_related('movie').filter(user=userid)
        if userInput.count()== 0:
            recommenderQuery=None
            userInput=None
        else:
            for item in userInput:
                C=[item.movie.title,item.rating]
                D+=[C]
            inputMovies=pd.DataFrame(D,columns=['title','rating'])
            print("Watched Movies by user dataframe")
            inputMovies['rating']=inputMovies['rating'].astype(str).astype(np.float)
            print(inputMovies.dtypes)

            #Filtering out the movies by title
            inputId = movies_df[movies_df['title'].isin(inputMovies['title'].tolist())]
            #Then merging it so we can get the movieId. It's implicitly merging it by title.
            inputMovies = pd.merge(inputId, inputMovies)
            # #Dropping information we won't use from the input dataframe
            # inputMovies = inputMovies.drop('year', 1)
            #Final input dataframe
            #If a movie you added in above isn't here, then it might not be in the original 
            #dataframe or it might spelled differently, please check capitalisation.
            print(inputMovies)

            #Filtering out users that have watched movies that the input has watched and storing it
            userSubset = rating_df[rating_df['movieId'].isin(inputMovies['movieId'].tolist())]
            print(userSubset.head())

            #Groupby creates several sub dataframes where they all have the same value in the column specified as the parameter
            userSubsetGroup = userSubset.groupby(['userId'])
            
            #print(userSubsetGroup.get_group(7))

            #Sorting it so users with movie most in common with the input will have priority
            userSubsetGroup = sorted(userSubsetGroup,  key=lambda x: len(x[1]), reverse=True)

            print(userSubsetGroup[0:])


            userSubsetGroup = userSubsetGroup[0:]


            #Store the Pearson Correlation in a dictionary, where the key is the user Id and the value is the coefficient
            pearsonCorrelationDict = {}

        #For every user group in our subset
            for name, group in userSubsetGroup:
            #Let's start by sorting the input and current user group so the values aren't mixed up later on
                group = group.sort_values(by='movieId')
                inputMovies = inputMovies.sort_values(by='movieId')
                #Get the N for the formula
                nRatings = len(group)
                #Get the review scores for the movies that they both have in common
                temp_df = inputMovies[inputMovies['movieId'].isin(group['movieId'].tolist())]
                #And then store them in a temporary buffer variable in a list format to facilitate future calculations
                tempRatingList = temp_df['rating'].tolist()
                #Let's also put the current user group reviews in a list format
                tempGroupList = group['rating'].tolist()
                #Now let's calculate the pearson correlation between two users, so called, x and y
                Sxx = sum([i**2 for i in tempRatingList]) - pow(sum(tempRatingList),2)/float(nRatings)
                Syy = sum([i**2 for i in tempGroupList]) - pow(sum(tempGroupList),2)/float(nRatings)
                Sxy = sum( i*j for i, j in zip(tempRatingList, tempGroupList)) - sum(tempRatingList)*sum(tempGroupList)/float(nRatings)
                
                #If the denominator is different than zero, then divide, else, 0 correlation.
                if Sxx != 0 and Syy != 0:
                    pearsonCorrelationDict[name] = Sxy/sqrt(Sxx*Syy)
                else:
                    pearsonCorrelationDict[name] = 0

            print(pearsonCorrelationDict.items())

            pearsonDF = pd.DataFrame.from_dict(pearsonCorrelationDict, orient='index')
            pearsonDF.columns = ['similarityIndex']
            pearsonDF['userId'] = pearsonDF.index
            pearsonDF.index = range(len(pearsonDF))
            print(pearsonDF.head())

            topUsers=pearsonDF.sort_values(by='similarityIndex', ascending=False)[0:]
            print(topUsers.head())

            topUsersRating=topUsers.merge(rating_df, left_on='userId', right_on='userId', how='inner')
            topUsersRating.head()

                #Multiplies the similarity by the user's ratings
            topUsersRating['weightedRating'] = topUsersRating['similarityIndex']*topUsersRating['rating']
            topUsersRating.head()


            #Applies a sum to the topUsers after grouping it up by userId
            tempTopUsersRating = topUsersRating.groupby('movieId').sum()[['similarityIndex','weightedRating']]
            tempTopUsersRating.columns = ['sum_similarityIndex','sum_weightedRating']
            tempTopUsersRating.head()

            #Creates an empty dataframe
            recommendation_df = pd.DataFrame()
            #Now we take the weighted average
            recommendation_df['weighted average recommendation score'] = tempTopUsersRating['sum_weightedRating']/tempTopUsersRating['sum_similarityIndex']
            recommendation_df['movieId'] = tempTopUsersRating.index
            recommendation_df.head()

            recommendation_df = recommendation_df.sort_values(by='weighted average recommendation score', ascending=False)
            recommender=movies_df.loc[movies_df['movieId'].isin(recommendation_df.head(6)['movieId'].tolist())]
            print(recommender)
            return recommender.to_dict('records')
            

            




def signup(request):
    if not request.user.is_authenticated:
        if request.method=='POST':
            fm=SignUpForm(request.POST)
            if fm.is_valid():
                user=fm.save()
                group=Group.objects.get(name='Editor')
                user.groups.add(group)
                messages.success(request,'Account Created Successfully!!!')
        else:
            if not request.user.is_authenticated:
                fm=SignUpForm()
        return render(request,'MovieRecommender/signup.html',{'form':fm})
    else:
        return HttpResponseRedirect('/home/')

def user_login(request):
    if not request.user.is_authenticated:
        if request.method=='POST':
            fm=LoginForm(request=request,data=request.POST)
            if fm.is_valid():
                uname=fm.cleaned_data['username']
                upass=fm.cleaned_data['password']
                user=authenticate(username=uname,password=upass)
                if user is not None:
                    login(request,user)
                    messages.success(request,'Logged in Successfully!!')
                    return HttpResponseRedirect('/dashboard/')
        else:
            fm=LoginForm()
        return render(request,'MovieRecommender/login.html',{'form':fm})
    else:
        return HttpResponseRedirect('/dashboard/')



def home(request):
    params=filterMovieByGenre()
    params['recommended']=generateRecommendation(request)
    return render(request,'MovieRecommender/home.html',params)

def addmovie(request):
    if request.user.is_authenticated:
        if request.method=='POST':
            fm=AddMovieForm(request.POST,request.FILES)
            if fm.is_valid():
                fm.save()
                messages.success(request,'Movie Added Successfully!!!')
        else:
            fm=AddMovieForm()
        return render(request,'MovieRecommender/addmovie.html',{'form':fm})
    else:
        return HttpResponseRedirect('/login/')


def dashboard(request):
    if request.user.is_authenticated: 
        params=filterMovieByGenre()
        params['user']=request.user
        if request.method=='POST':
            userid=request.POST.get('userid')
            movieid=request.POST.get('movieid')
            movie=Movie.objects.all()
            u=User.objects.get(pk=userid)

Movie-Recommendation/Movie-Recommendation/templates/MovieRecommender/addmovie.html
{% extends 'MovieRecommender/base.html' %}
{% block title %}Add Movie{% endblock title %}
{% block css %}
body
{
    background:url(https://i.pinimg.com/564x/03/d6/fa/03d6fae739dffa00f36705aa6d9bdfca.jpg);
}
span {
  padding:14px;
  height:5px;
  border-top-left-radius:20%;
  border-top-right-radius:80%;
  text-align: center;
  background-color: #73c2dd;
}
h4 
{
  padding:10px;
  flex: 1 1 auto;
  text-align: center;
  background-color: #73c2dd;
}
{% endblock css %}
{%block content%}
 {%if perms.MovieRecommender.add_movie%}
<div class="container  mt-2 p-5 mb-2">
<h1 class="text-center text-light">Add Movie</h1>  
  <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for fm in form  %}
        <span class="text-light font-weight-bold"><font face="Georgia" size="4" color="black" >{{fm.label_tag}}</font></span>
        <p>{{fm}}</p>
        {% endfor %}
        <input type="submit" class="btn btn-primary" value="Add">
        </form><br>
        {% if messages %}
        {%for msg in messages%}
        {% if msg %}   <div class="alert alert-success">{{msg}}</div>{% endif %}
        {%endfor%}
        {% endif %}
</form>
</div>
{% else %}
<h4 class="text-light mt-2 ml-2">
  <font face="Georgia" size="6" color="black" >Only Admin has Permission To Add Movie</font></h4>
{% endif %}
{%endblock content%} 

Movie-Recommendation/Movie-Recommendation/templates/MovieRecommender/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <title>{% block title %}  {% endblock title %}</title>
    <style>
    {% block css %}
    {% endblock css %}
    </style>
  </head>
  <body>
    {% include 'MovieRecommender/navbar.html' %}
                        {% block content %}



                        {% endblock content %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

Movie-Recommendation/Movie-Recommendation/templates/MovieRecommender/dashboard.html
{% extends 'MovieRecommender/base.html' %}
{% block title %}Dashboard{% endblock title %}
{% block css %}
body
{
       background:url(https://i.pinimg.com/564x/03/d6/fa/03d6fae739dffa00f36705aa6d9bdfca.jpg);
 }
 .col-md-3
 {
 display: inline-flex;
 margin-left:-4px;
 }
 .col-md-3 img
 {
 width: 238px;
 height: 300px;
 }
 .container carousel-inner no-padding
 {
   height: 800px;
 }

 h4 
 {
   padding:10px;
   flex: 1 1 auto;
   text-align: center;
   background-color: #73c2dd;
 }
 h4 font 
 {
   color:black;
 }
 .carousel-control-prev, .carousel-control-next
 {
 top: auto;
 bottom: auto;
 padding-top: 200px;
 }
 body .no-padding
 {
  padding-left: 0,
  padding-right: 0;
 }
 .card:hover 
 {
      background-color:#ffe443;
 }
.wrapper
{
margin-bottom:200px;
}


 {% endblock %}

{% block content %}
<div class="container wrapper">
     {% if messages %}
                {%for msg in messages%}
                {% if msg %}   <div class="alert alert-{{msg.tags}} alert-dismissible fade show font-weight-bold text-primary w-50 ml-3 mt-5">{{msg}} <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button></div>{% endif %}
                {%endfor%}
                {% endif %}

    <!--Slideshow starts here -->
    {% for movie, range, nSlides in allMovies %}
    <h4 class="my-4 text-light"><font face="Georgia" size="5"  >{{movie.0.genres}}</font></h4>
<div class="row">
    <div id="demo{{forloop.counter}}" class="col carousel slide my-3" data-ride="carousel">
    <ul class="carousel-indicators">
      <li data-target="#demo{{forloop.counter}}" data-slide-to="0" class="active"></li>

       {% for i in range %}
      <li data-target="#demo{{forloop.parentloop.counter}}" data-slide-to="{{i}}" ></li>
      {% endfor %}
    </ul>


    <div class="container carousel-inner no-padding">

      <div class="carousel-item active">
        {% for i in movie|slice:"0:"%}
        <div class="col-xs-3 col-sm-3 col-md-3">
         <div class="card" style="width: 18rem">
             <img class="card-img-top" src="{{i.image.url}}"  alt="Card image cap" height="250px" width="200px">    
                      <div class="card-body">
                        <h5 class="card-title"><font face="Georgia" size="4" >{{i.title}}</font></h5>
                         <form action="" method="post" class="range-field">
                                                                        {% csrf_token %}  
                                                                        <input type="hidden" name="movieid" value="{{i.id}}"/>
                                                                        <input type="hidden" name="userid" value="{{user.id}}"/> 
                                                                        {{rform.as_p}}
                                                                        <div class="showrating">
                                                                        
                                                                        </div>
                                                                        <input type="submit" class="btn btn-primary" value="Submit">
                        </form>
                      </div>       
                      <div class="card-footer">
                        <small class="text-muted"><font face="Georgia" size="3" >{{i.genres}}</font></small>
                        <small class="text-muted" style="float: right;"><font face="verdana" size="3" >{{i.movieduration}}</font></small>
                     </div>
          </div>
        </div>
        {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}
      </div><div class="carousel-item">
        {% endif %}

        {% endfor %}
    </div>



</div>
</div>
    <!-- left and right controls for the slide -->
    <a class="carousel-control-prev" href="#demo{{forloop.counter}}" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo{{forloop.counter}}" data-slide="next">
        <span class="carousel-control-next-icon"></span>
    </a>
        </div>
    {% endfor %}
</div>
 {% endblock %}




 

Movie-Recommendation/Movie-Recommendation/templates/MovieRecommender/home.html
{% extends 'MovieRecommender/base.html' %}
{% block title %}Home{% endblock title %}
{% block css %}
         body
          {
               background:url(https://i.pinimg.com/564x/03/d6/fa/03d6fae739dffa00f36705aa6d9bdfca.jpg)
          }
          .col-md-3
          {
          display: inline-flex;
          margin-left:-4px;
          }
        .col-md-3 img
        {
          width: 235px;
          height: 300px;
        }
        h4 
        {
            padding:10px;
            flex: 1 1 auto;
            text-align: center;
            background-color: #73c2dd;
        }
       h4 font 
       {
            color:black;
      }
       .card:hover 
       {
            background-color:#ffe443;
       }
       .carousel-control-prev,.carousel-control-next
       {
          top: auto;
          bottom: auto;
          padding-top: 50px;
        }
        body .no-padding
        {
           padding-left: 0,
           padding-right: 0;
        }
        .wrapper
        {
        margin-bottom:200px;
        }
 {% endblock %}

{% block content %}
<div class="container wrapper">
{% if  recommended%}
<h4 class="my-4 text-light"><font face="Georgia" size="5" >Recommended Movie For You</font></u></h4>
<div class="row">
{% for item in recommended %}
<div class="col-4 mb-2">
        <div class="card" style="width: 15rem">
                <img class="card-img-top" src="{{item.image}}"  alt="Card image cap" height="250px" width="200px">           
                <div class="card-footer">
                <small class="text-muted"><font face="Georgia" size="4" >{{item.genres}}</font></small>
                <small class="text-muted" style="float:right"><font face="verdana" size="3" >{{item.movieduration}}</font></small>
                </div>
        </div>
</div>
{% endfor %}
</div>
{% else %}
<h5 class="my-4 text-light">No Recommended Movie Found</u></h5>
{% endif %}
<br><br>
    <!--Slideshow starts here -->
    {% for movie, range, nSlides in allMovies %}
    <h4 class="my-4 text-light"><font face="Georgia" size="5"  >{{movie.0.genres}}</font></h4>
<div class="row">
    <div id="demo{{forloop.counter}}" class="col carousel slide my-3" data-ride="carousel">
       {% for i in range %}
      <li data-target="#demo{{forloop.parentloop.counter}}" data-slide-to="{{i}}" ></li>
      {% endfor %}
    <div class="container carousel-inner no-padding">
      <div class="carousel-item active">
        {% for i in movie|slice:"0:"%}
        <div class="col-xs-3 col-sm-3 col-md-3">
          <div class=card style="width: 18rem">
             <img class="card-img-top" src="{{i.image.url}}"  alt="Card image cap" height="250px" width="200px">    
                      <div class="card-body">
                        <h5 class="card-title"><font face="Georgia" size="4" >{{i.title}}</font></h5>
                      </div>       
                      <div class="card-footer">
                        <small class="text-muted"><font face="Georgia" size="3" >{{i.genres}}</font></small>
                        <small class="text-muted" style="float: right;"><font face="verdana" size="3" >{{i.movieduration}}</font></small>
                     </div>
          </div>
        </div>
        {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}
      </div>
      <div class="carousel-item">
        {% endif %}
        {% endfor %}
      </div>
 </div>
 <!-- left and right controls for the slide -->
<a class="carousel-control-prev" href="#demo{{forloop.counter}}" data-slide="prev">
  <span class="carousel-control-prev-icon"></span>
</a>
<a class="carousel-control-next" href="#demo{{forloop.counter}}" data-slide="next">
  <span class="carousel-control-next-icon"></span>
</a>
  </div>
</div>
    {% endfor %}
</div>
 {% endblock %}




 

Movie-Recommendation/Movie-Recommendation/templates/MovieRecommender/login.html
{% extends 'MovieRecommender/base.html' %}
{% block title %}Login{% endblock title %}
{% block css %}
span {
    padding:14px;
    height:5px;
    border-top-left-radius:20%;
    border-top-right-radius:80%;
    text-align: center;
    background-color: #73c2dd;
  }
body{
    background:url(https://i.pinimg.com/564x/03/d6/fa/03d6fae739dffa00f36705aa6d9bdfca.jpg);
   }
{% endblock css %}
{% block content %}
<div class="container p-5 mb-5">
<form action="" method="post" novalidate>
{% csrf_token %}
{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger">{{error}}</div>
{% endfor %}
{% endif %} <br>
{% for fm in  form %}
<span class="text-light"><font face="Georgia" size="4" color="black" >{{fm.label_tag}}</font></span>
<p>
{{fm}}
</p>
{% if fm.errors  %}
<div class="alert alert-danger">
{{fm.errors|striptags}}
</div>
{% endif %}
{% endfor %} <br>
<input type="submit" value="Login" class="btn btn-primary"><br>
</form>
</div>
{% endblock content %}

Movie-Recommendation/Movie-Recommendation/templates/MovieRecommender/signup.html
{% extends 'MovieRecommender/base.html' %}
{% block title %}Signup{% endblock title %}
{% block css %}
body{
    background:url(https://i.pinimg.com/564x/03/d6/fa/03d6fae739dffa00f36705aa6d9bdfca.jpg);
}
span {
  padding:14px;
  height:5px;
  border-top-left-radius:20%;
  border-top-right-radius:80%;
  text-align: center;
  background-color: #73c2dd;
}
.wrapper{
        margin-bottom:200px;
}

{% endblock css %}
{% block content %}

<div class="container p-5 mb-5 wrapper">
     {% if messages %}
                {%for msg in messages%}
                {% if msg %}   <div class="alert alert-{{msg.tags}} alert-dismissible fade show font-weight-bold text-primary w-50 ml-3 mt-5">{{msg}} <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button></div>{% endif %}
        {%endfor%}
        {% endif %}

<form action="" method="post" novalidate>
{% csrf_token %}
{% for fm in form %}
<span class="text-light"><font face="Georgia" size="4" color="black" >{{fm.label_tag}}</font></span>
<div class="form-group">
{{fm}}
</div>
{% if fm.errors %}
<div class="alert alert-danger lert-dismissible fade show">
{{fm.errors|striptags}}
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>

</div>
{% endif %}
{% endfor %}<br/>
  <input type="submit" value="submit" class="btn btn-primary">
</form>
</div>
{% endblock content %}